name: first
on: [push]
#on:
#  #https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
#  schedule:
#    # https://crontab.guru/examples.html
#    - cron: '*/15 * * * *'

jobs:
  job1:
    name: first
    runs-on: ubuntu-latest
    steps:
      - name: s_one
        uses: actions/checkout@v2
      - name: s_two
        run: env | sort
  job2:
    name: second
    runs-on: windows-latest
    steps:
      - name: s_one
        uses: actions/checkout@v2
      - name: s_two
        run: "Get-ChildItem Env: | Sort-Object Name"
